// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SsiApi.Data;

#nullable disable

namespace SsiApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119180000_initialMigrationOnOracle")]
    partial class initialMigrationOnOracle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ssi", b =>
                {
                    b.Property<int>("SsiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ssi_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SsiId"));

                    b.Property<int>("Andamento")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("andamento");

                    b.Property<string>("ChapaSolicitante")
                        .IsRequired()
                        .HasColumnType("char(6)")
                        .HasColumnName("chapa_solicitante");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_registro");

                    b.Property<string>("NomeSolicitante")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome_solicitante");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int")
                        .HasColumnName("servico_id");

                    b.HasKey("SsiId");

                    b.HasIndex("ChapaSolicitante");

                    b.HasIndex("ServicoId");

                    b.ToTable("ssi", (string)null);
                });

            modelBuilder.Entity("SsiApi.Models.Servico", b =>
                {
                    b.Property<int>("ServicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("servico_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ServicoId"));

                    b.Property<string>("AreaServico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("area_servico");

                    b.Property<string>("Mostrar")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("mostrar");

                    b.Property<string>("NomeServico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_servico");

                    b.HasKey("ServicoId");

                    b.ToTable("servico", (string)null);
                });

            modelBuilder.Entity("SsiApi.Models.Usuario", b =>
                {
                    b.Property<string>("Chapa")
                        .HasColumnType("char(6)")
                        .HasColumnName("chapa");

                    b.Property<string>("AreaTecnico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("area_tecnico");

                    b.Property<string>("Mostrar")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("mostrar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Ramal")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .HasColumnName("ramal");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Chapa");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Ssi", b =>
                {
                    b.HasOne("SsiApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("ChapaSolicitante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SsiApi.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servico");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
